# Use uma imagem base com Node.js
FROM node:16-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Instala as dependências do projeto
COPY package*.json ./
RUN npm install



# Copia o código-fonte da aplicação para o diretório de trabalho
COPY . .

# Exponha a porta que será usada pela aplicação Vue.js
EXPOSE 5173

# Comando para iniciar a aplicação em modo de desenvolvimento
CMD ["npm", "run", "dev"],
