default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1234
  host: 172.19.0.2
  port: 3306
  database: healthsync
  timeout: 5000

development:
  <<: *default
  database: healthsync

test:
  <<: *default
  database: healthsync

production:
  <<: *default
  database: healthsync
